version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/MV_WebApp_New_Syntax"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
    target-branch: main
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
    target-branch: main
